/**
 * @fileoverview gRPC-Web generated client stub for appointment
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.32.1
// source: appointment.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as appointment_pb from './appointment_pb'; // proto import: "appointment.proto"


export class AppointmentServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateAppointment = new grpcWeb.MethodDescriptor(
    '/appointment.AppointmentService/CreateAppointment',
    grpcWeb.MethodType.UNARY,
    appointment_pb.CreateAppointmentRequest,
    appointment_pb.CreateAppointmentResponse,
    (request: appointment_pb.CreateAppointmentRequest) => {
      return request.serializeBinary();
    },
    appointment_pb.CreateAppointmentResponse.deserializeBinary
  );

  createAppointment(
    request: appointment_pb.CreateAppointmentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<appointment_pb.CreateAppointmentResponse>;

  createAppointment(
    request: appointment_pb.CreateAppointmentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: appointment_pb.CreateAppointmentResponse) => void): grpcWeb.ClientReadableStream<appointment_pb.CreateAppointmentResponse>;

  createAppointment(
    request: appointment_pb.CreateAppointmentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: appointment_pb.CreateAppointmentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/appointment.AppointmentService/CreateAppointment',
        request,
        metadata || {},
        this.methodDescriptorCreateAppointment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/appointment.AppointmentService/CreateAppointment',
    request,
    metadata || {},
    this.methodDescriptorCreateAppointment);
  }

  methodDescriptorListAppointments = new grpcWeb.MethodDescriptor(
    '/appointment.AppointmentService/ListAppointments',
    grpcWeb.MethodType.UNARY,
    appointment_pb.ListAppointmentsRequest,
    appointment_pb.ListAppointmentsResponse,
    (request: appointment_pb.ListAppointmentsRequest) => {
      return request.serializeBinary();
    },
    appointment_pb.ListAppointmentsResponse.deserializeBinary
  );

  listAppointments(
    request: appointment_pb.ListAppointmentsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<appointment_pb.ListAppointmentsResponse>;

  listAppointments(
    request: appointment_pb.ListAppointmentsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: appointment_pb.ListAppointmentsResponse) => void): grpcWeb.ClientReadableStream<appointment_pb.ListAppointmentsResponse>;

  listAppointments(
    request: appointment_pb.ListAppointmentsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: appointment_pb.ListAppointmentsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/appointment.AppointmentService/ListAppointments',
        request,
        metadata || {},
        this.methodDescriptorListAppointments,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/appointment.AppointmentService/ListAppointments',
    request,
    metadata || {},
    this.methodDescriptorListAppointments);
  }

  methodDescriptorDeleteAppointment = new grpcWeb.MethodDescriptor(
    '/appointment.AppointmentService/DeleteAppointment',
    grpcWeb.MethodType.UNARY,
    appointment_pb.DeleteAppointmentRequest,
    appointment_pb.DeleteAppointmentResponse,
    (request: appointment_pb.DeleteAppointmentRequest) => {
      return request.serializeBinary();
    },
    appointment_pb.DeleteAppointmentResponse.deserializeBinary
  );

  deleteAppointment(
    request: appointment_pb.DeleteAppointmentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<appointment_pb.DeleteAppointmentResponse>;

  deleteAppointment(
    request: appointment_pb.DeleteAppointmentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: appointment_pb.DeleteAppointmentResponse) => void): grpcWeb.ClientReadableStream<appointment_pb.DeleteAppointmentResponse>;

  deleteAppointment(
    request: appointment_pb.DeleteAppointmentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: appointment_pb.DeleteAppointmentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/appointment.AppointmentService/DeleteAppointment',
        request,
        metadata || {},
        this.methodDescriptorDeleteAppointment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/appointment.AppointmentService/DeleteAppointment',
    request,
    metadata || {},
    this.methodDescriptorDeleteAppointment);
  }

}

