// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "appointment.proto" (package "appointment", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message appointment.Appointment
 */
export interface Appointment {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string date = 3
     */
    date: string; // YYYY-MM-DD
    /**
     * @generated from protobuf field: string time = 4
     */
    time: string; // HH:mm
}
/**
 * Create
 *
 * @generated from protobuf message appointment.CreateAppointmentRequest
 */
export interface CreateAppointmentRequest {
    /**
     * @generated from protobuf field: string title = 1
     */
    title: string;
    /**
     * @generated from protobuf field: string date = 2
     */
    date: string;
    /**
     * @generated from protobuf field: string time = 3
     */
    time: string;
}
/**
 * @generated from protobuf message appointment.CreateAppointmentResponse
 */
export interface CreateAppointmentResponse {
    /**
     * @generated from protobuf field: appointment.Appointment appointment = 1
     */
    appointment?: Appointment;
}
/**
 * List
 *
 * @generated from protobuf message appointment.ListAppointmentsRequest
 */
export interface ListAppointmentsRequest {
}
/**
 * @generated from protobuf message appointment.ListAppointmentsResponse
 */
export interface ListAppointmentsResponse {
    /**
     * @generated from protobuf field: repeated appointment.Appointment appointments = 1
     */
    appointments: Appointment[];
}
/**
 * Delete
 *
 * @generated from protobuf message appointment.DeleteAppointmentRequest
 */
export interface DeleteAppointmentRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message appointment.DeleteAppointmentResponse
 */
export interface DeleteAppointmentResponse {
}
/**
 * Search
 *
 * @generated from protobuf message appointment.SearchAppointmentsRequest
 */
export interface SearchAppointmentsRequest {
    /**
     * @generated from protobuf field: string title = 1
     */
    title: string; // optional: search by title
    /**
     * @generated from protobuf field: string date = 2
     */
    date: string; // optional: search by date YYYY-MM-DD
}
// @generated message type with reflection information, may provide speed optimized methods
class Appointment$Type extends MessageType<Appointment> {
    constructor() {
        super("appointment.Appointment", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "time", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Appointment>): Appointment {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.title = "";
        message.date = "";
        message.time = "";
        if (value !== undefined)
            reflectionMergePartial<Appointment>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Appointment): Appointment {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string date */ 3:
                    message.date = reader.string();
                    break;
                case /* string time */ 4:
                    message.time = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Appointment, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string date = 3; */
        if (message.date !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.date);
        /* string time = 4; */
        if (message.time !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.time);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message appointment.Appointment
 */
export const Appointment = new Appointment$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateAppointmentRequest$Type extends MessageType<CreateAppointmentRequest> {
    constructor() {
        super("appointment.CreateAppointmentRequest", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "time", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CreateAppointmentRequest>): CreateAppointmentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.date = "";
        message.time = "";
        if (value !== undefined)
            reflectionMergePartial<CreateAppointmentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateAppointmentRequest): CreateAppointmentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* string date */ 2:
                    message.date = reader.string();
                    break;
                case /* string time */ 3:
                    message.time = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateAppointmentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* string date = 2; */
        if (message.date !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.date);
        /* string time = 3; */
        if (message.time !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.time);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message appointment.CreateAppointmentRequest
 */
export const CreateAppointmentRequest = new CreateAppointmentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateAppointmentResponse$Type extends MessageType<CreateAppointmentResponse> {
    constructor() {
        super("appointment.CreateAppointmentResponse", [
            { no: 1, name: "appointment", kind: "message", T: () => Appointment }
        ]);
    }
    create(value?: PartialMessage<CreateAppointmentResponse>): CreateAppointmentResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateAppointmentResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateAppointmentResponse): CreateAppointmentResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* appointment.Appointment appointment */ 1:
                    message.appointment = Appointment.internalBinaryRead(reader, reader.uint32(), options, message.appointment);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateAppointmentResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* appointment.Appointment appointment = 1; */
        if (message.appointment)
            Appointment.internalBinaryWrite(message.appointment, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message appointment.CreateAppointmentResponse
 */
export const CreateAppointmentResponse = new CreateAppointmentResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListAppointmentsRequest$Type extends MessageType<ListAppointmentsRequest> {
    constructor() {
        super("appointment.ListAppointmentsRequest", []);
    }
    create(value?: PartialMessage<ListAppointmentsRequest>): ListAppointmentsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListAppointmentsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListAppointmentsRequest): ListAppointmentsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListAppointmentsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message appointment.ListAppointmentsRequest
 */
export const ListAppointmentsRequest = new ListAppointmentsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListAppointmentsResponse$Type extends MessageType<ListAppointmentsResponse> {
    constructor() {
        super("appointment.ListAppointmentsResponse", [
            { no: 1, name: "appointments", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Appointment }
        ]);
    }
    create(value?: PartialMessage<ListAppointmentsResponse>): ListAppointmentsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.appointments = [];
        if (value !== undefined)
            reflectionMergePartial<ListAppointmentsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListAppointmentsResponse): ListAppointmentsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated appointment.Appointment appointments */ 1:
                    message.appointments.push(Appointment.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListAppointmentsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated appointment.Appointment appointments = 1; */
        for (let i = 0; i < message.appointments.length; i++)
            Appointment.internalBinaryWrite(message.appointments[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message appointment.ListAppointmentsResponse
 */
export const ListAppointmentsResponse = new ListAppointmentsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteAppointmentRequest$Type extends MessageType<DeleteAppointmentRequest> {
    constructor() {
        super("appointment.DeleteAppointmentRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteAppointmentRequest>): DeleteAppointmentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteAppointmentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteAppointmentRequest): DeleteAppointmentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteAppointmentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message appointment.DeleteAppointmentRequest
 */
export const DeleteAppointmentRequest = new DeleteAppointmentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteAppointmentResponse$Type extends MessageType<DeleteAppointmentResponse> {
    constructor() {
        super("appointment.DeleteAppointmentResponse", []);
    }
    create(value?: PartialMessage<DeleteAppointmentResponse>): DeleteAppointmentResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DeleteAppointmentResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteAppointmentResponse): DeleteAppointmentResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteAppointmentResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message appointment.DeleteAppointmentResponse
 */
export const DeleteAppointmentResponse = new DeleteAppointmentResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchAppointmentsRequest$Type extends MessageType<SearchAppointmentsRequest> {
    constructor() {
        super("appointment.SearchAppointmentsRequest", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "date", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SearchAppointmentsRequest>): SearchAppointmentsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.date = "";
        if (value !== undefined)
            reflectionMergePartial<SearchAppointmentsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchAppointmentsRequest): SearchAppointmentsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* string date */ 2:
                    message.date = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchAppointmentsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* string date = 2; */
        if (message.date !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.date);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message appointment.SearchAppointmentsRequest
 */
export const SearchAppointmentsRequest = new SearchAppointmentsRequest$Type();
/**
 * @generated ServiceType for protobuf service appointment.AppointmentService
 */
export const AppointmentService = new ServiceType("appointment.AppointmentService", [
    { name: "CreateAppointment", options: {}, I: CreateAppointmentRequest, O: CreateAppointmentResponse },
    { name: "ListAppointments", options: {}, I: ListAppointmentsRequest, O: ListAppointmentsResponse },
    { name: "DeleteAppointment", options: {}, I: DeleteAppointmentRequest, O: DeleteAppointmentResponse },
    { name: "SearchAppointments", options: {}, I: SearchAppointmentsRequest, O: ListAppointmentsResponse }
]);
