/**
 * @fileoverview gRPC-Web generated client stub for appointment
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.32.1
// source: proto/appointment.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.appointment = require('./appointment_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.appointment.AppointmentServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.appointment.AppointmentServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.appointment.CreateAppointmentRequest,
 *   !proto.appointment.CreateAppointmentResponse>}
 */
const methodDescriptor_AppointmentService_CreateAppointment = new grpc.web.MethodDescriptor(
  '/appointment.AppointmentService/CreateAppointment',
  grpc.web.MethodType.UNARY,
  proto.appointment.CreateAppointmentRequest,
  proto.appointment.CreateAppointmentResponse,
  /**
   * @param {!proto.appointment.CreateAppointmentRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.appointment.CreateAppointmentResponse.deserializeBinary
);


/**
 * @param {!proto.appointment.CreateAppointmentRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.appointment.CreateAppointmentResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.appointment.CreateAppointmentResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.appointment.AppointmentServiceClient.prototype.createAppointment =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/appointment.AppointmentService/CreateAppointment',
      request,
      metadata || {},
      methodDescriptor_AppointmentService_CreateAppointment,
      callback);
};


/**
 * @param {!proto.appointment.CreateAppointmentRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.appointment.CreateAppointmentResponse>}
 *     Promise that resolves to the response
 */
proto.appointment.AppointmentServicePromiseClient.prototype.createAppointment =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/appointment.AppointmentService/CreateAppointment',
      request,
      metadata || {},
      methodDescriptor_AppointmentService_CreateAppointment);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.appointment.ListAppointmentsRequest,
 *   !proto.appointment.ListAppointmentsResponse>}
 */
const methodDescriptor_AppointmentService_ListAppointments = new grpc.web.MethodDescriptor(
  '/appointment.AppointmentService/ListAppointments',
  grpc.web.MethodType.UNARY,
  proto.appointment.ListAppointmentsRequest,
  proto.appointment.ListAppointmentsResponse,
  /**
   * @param {!proto.appointment.ListAppointmentsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.appointment.ListAppointmentsResponse.deserializeBinary
);


/**
 * @param {!proto.appointment.ListAppointmentsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.appointment.ListAppointmentsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.appointment.ListAppointmentsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.appointment.AppointmentServiceClient.prototype.listAppointments =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/appointment.AppointmentService/ListAppointments',
      request,
      metadata || {},
      methodDescriptor_AppointmentService_ListAppointments,
      callback);
};


/**
 * @param {!proto.appointment.ListAppointmentsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.appointment.ListAppointmentsResponse>}
 *     Promise that resolves to the response
 */
proto.appointment.AppointmentServicePromiseClient.prototype.listAppointments =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/appointment.AppointmentService/ListAppointments',
      request,
      metadata || {},
      methodDescriptor_AppointmentService_ListAppointments);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.appointment.DeleteAppointmentRequest,
 *   !proto.appointment.DeleteAppointmentResponse>}
 */
const methodDescriptor_AppointmentService_DeleteAppointment = new grpc.web.MethodDescriptor(
  '/appointment.AppointmentService/DeleteAppointment',
  grpc.web.MethodType.UNARY,
  proto.appointment.DeleteAppointmentRequest,
  proto.appointment.DeleteAppointmentResponse,
  /**
   * @param {!proto.appointment.DeleteAppointmentRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.appointment.DeleteAppointmentResponse.deserializeBinary
);


/**
 * @param {!proto.appointment.DeleteAppointmentRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.appointment.DeleteAppointmentResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.appointment.DeleteAppointmentResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.appointment.AppointmentServiceClient.prototype.deleteAppointment =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/appointment.AppointmentService/DeleteAppointment',
      request,
      metadata || {},
      methodDescriptor_AppointmentService_DeleteAppointment,
      callback);
};


/**
 * @param {!proto.appointment.DeleteAppointmentRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.appointment.DeleteAppointmentResponse>}
 *     Promise that resolves to the response
 */
proto.appointment.AppointmentServicePromiseClient.prototype.deleteAppointment =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/appointment.AppointmentService/DeleteAppointment',
      request,
      metadata || {},
      methodDescriptor_AppointmentService_DeleteAppointment);
};


module.exports = proto.appointment;

