// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "appointment.proto" (package "appointment", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AppointmentService } from "./appointment";
import type { DeleteAppointmentResponse } from "./appointment";
import type { DeleteAppointmentRequest } from "./appointment";
import type { ListAppointmentsResponse } from "./appointment";
import type { ListAppointmentsRequest } from "./appointment";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateAppointmentResponse } from "./appointment";
import type { CreateAppointmentRequest } from "./appointment";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service appointment.AppointmentService
 */
export interface IAppointmentServiceClient {
    /**
     * @generated from protobuf rpc: CreateAppointment
     */
    createAppointment(input: CreateAppointmentRequest, options?: RpcOptions): UnaryCall<CreateAppointmentRequest, CreateAppointmentResponse>;
    /**
     * @generated from protobuf rpc: ListAppointments
     */
    listAppointments(input: ListAppointmentsRequest, options?: RpcOptions): UnaryCall<ListAppointmentsRequest, ListAppointmentsResponse>;
    /**
     * @generated from protobuf rpc: DeleteAppointment
     */
    deleteAppointment(input: DeleteAppointmentRequest, options?: RpcOptions): UnaryCall<DeleteAppointmentRequest, DeleteAppointmentResponse>;
}
/**
 * @generated from protobuf service appointment.AppointmentService
 */
export class AppointmentServiceClient implements IAppointmentServiceClient, ServiceInfo {
    typeName = AppointmentService.typeName;
    methods = AppointmentService.methods;
    options = AppointmentService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateAppointment
     */
    createAppointment(input: CreateAppointmentRequest, options?: RpcOptions): UnaryCall<CreateAppointmentRequest, CreateAppointmentResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateAppointmentRequest, CreateAppointmentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAppointments
     */
    listAppointments(input: ListAppointmentsRequest, options?: RpcOptions): UnaryCall<ListAppointmentsRequest, ListAppointmentsResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAppointmentsRequest, ListAppointmentsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteAppointment
     */
    deleteAppointment(input: DeleteAppointmentRequest, options?: RpcOptions): UnaryCall<DeleteAppointmentRequest, DeleteAppointmentResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteAppointmentRequest, DeleteAppointmentResponse>("unary", this._transport, method, opt, input);
    }
}
